### ISSUE TITLE
Bundle app credentials in the package

### ISSUE THREAD

**Issue by hadley** [RomanTsegelskyi/yummlyr#3]
There's no reason to each user create a yummly "application", when you can bundle one set of keys with the package.

**Comment by RomanTsegelskyi** [comment]
While I agree that it would be nice, the problem is that Yummly.com doesn't have free [plans](https://developer.yummly.com/#plans). Additionally the amount of calls is limited per day. So I am not sure if it is possible have the set of keys inside the package.

**Comment by hadley** [comment]
Ah got it - I misunderstood how the yummly auth worked.
